'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider } from 'react-redux';
import store from './store';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'deepSafe',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            {/* <body className={inter.className}>{children}</body> */}

            <body>
                <Provider store={store}>{children}</Provider>
            </body>
        </html>
    );
}
